stages:
  - publish
  - deploy

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  IMAGE_NAME_STAGE: "$CI_REGISTRY_IMAGE:stage-$CI_COMMIT_REF_NAME"
  CONTAINER_PROD_NAME: "cats-ui"
  CONTAINER_QA_NAME: "cats-ui-qa"

publish:docker:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --build-arg REACT_APP_CATS_API_URL=$REACT_APP_CATS_API_URL --build-arg REACT_APP_REACTION_URL=$REACT_APP_REACTION_URL --build-arg REACT_APP_PHOTOS_API_URL=$REACT_APP_PHOTOS_API_URL -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - tags

publish:docker-stage:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --build-arg REACT_APP_CATS_API_URL=$REACT_APP_CATS_API_URL_STAGE --build-arg REACT_APP_REACTION_URL=$REACT_APP_REACTION_URL_STAGE --build-arg REACT_APP_PHOTOS_API_URL=$REACT_APP_PHOTOS_API_URL_STAGE -t $IMAGE_NAME_STAGE .
    - docker push $IMAGE_NAME_STAGE
  only:
    - tags

deploy:docker-prod:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh $USER@$SERVER "(docker rm -f $CONTAINER_PROD_NAME) || true; docker pull $IMAGE_PROD_NAME; docker run -d --name $CONTAINER_PROD_NAME --net=$NETWORK --restart always -p $PROD_PORT:8080 -v $PHOTOS_PATH:/static/photos $IMAGE_PROD_NAME"
  only:
    - tags
  when: manual

deploy:docker-qa:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh $USER@$SERVER "(docker rm -f $CONTAINER_QA_NAME) || true; docker pull $IMAGE_QA_NAME; docker run -d --name $CONTAINER_QA_NAME --net=$NETWORK --restart always -p $QA_PORT:8080 -v $PHOTOS_PATH:/static/photos $IMAGE_QA_NAME"
  only: [merge_requests]
  when: manual
  except:
    variables:
      - $CI_MERGE_REQUEST_LABELS =~ /without-ci/
  
